<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>Cover</title>
        <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
        <style type="text/css">
            @page {
                margin: 0;
                padding: 0;
            }
            body, div, img {
                border-width: 0;
                height: 100%;
                margin: 0;
                max-width: 100%;
                padding: 0;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div><img alt="cover" src="<?php echo $cover; ?>"/></div>
    </body>
</html>